import type { ToolPreset, ToolId } from "../types";

// Easing curves for perfect-freehand thinning behavior.
const easeOutCubic = (t: number) => 1 - Math.pow(1 - t, 3);
const easeInOutQuad = (t: number) =>
  t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
const linear = (t: number) => t;

// Procreate-inspired tool set. Eight tools chosen to span the meaningful axes
// of stroke behavior so a future tool-aware model has interesting variety.
//
// Each preset's strokeOptions feed perfect-freehand directly. The `description`
// is shown as a tooltip in the picker.
// 13 tools, every one routed through libmypaint via a CC0 brush from
// `mypaint/mypaint-brushes`. The original 8 are 1:1 quality upgrades of our
// previous vector-rendered tools; the next 5 (charcoal, pastel, ballpen,
// calligraphy, knife) showcase MyPaint's natural-media variety.
//
// Each preset's `strokeOptions` (perfect-freehand) and `compositeOperation`
// remain present because they drive (a) the brief vector fallback while the
// wasm engine is loading and (b) any future tooling that wants a vector
// representation of a stroke. The actual on-canvas look comes from libmypaint
// once `engineReady` flips on.
//
// `radiusScale` is a per-tool feel calibration: each MyPaint brush has its
// own native size, so a "thickness slider = 5" needs different multipliers
// to look right across e.g. a hard-tip pencil and a wide watercolor wash.
export const TOOL_PRESETS: Record<ToolId, ToolPreset> = {
  pencil: {
    id: "pencil",
    label: "6B Pencil",
    description:
      "Soft graphite. Pressure controls width; tilt broadens the line. Real per-position grain via libmypaint.",
    defaultSize: 5,
    defaultOpacity: 0.55,
    strokeOptions: {
      thinning: 0.7,
      smoothing: 0.4,
      streamline: 0.4,
      simulatePressure: false,
      start: { taper: 14, cap: true },
      end: { taper: 22, cap: true },
      easing: easeOutCubic,
    },
    compositeOperation: "source-over",
    flatFill: true,
    texture: "pencil",
    tiltSizeBoost: 0.55,
    engine: "mypaint",
    brushFile: "pencil",
    radiusScale: 1.0,
  },
  inking: {
    id: "inking",
    label: "Studio Pen",
    description: "Clean ink line. Pressure controls width; sharp wet edges.",
    defaultSize: 5,
    defaultOpacity: 1,
    strokeOptions: {
      thinning: 0.55,
      smoothing: 0.7,
      streamline: 0.55,
      simulatePressure: false,
      start: { taper: 0, cap: true },
      end: { taper: 24, cap: true },
      easing: easeOutCubic,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "studio_pen",
    radiusScale: 1.0,
  },
  watercolor: {
    id: "watercolor",
    label: "Wash",
    description: "Build-up watercolor. Soft edges, layered tone, real glazing.",
    defaultSize: 36,
    defaultOpacity: 0.18,
    strokeOptions: {
      thinning: 0.2,
      smoothing: 0.85,
      streamline: 0.85,
      simulatePressure: false,
      start: { taper: 12, cap: true },
      end: { taper: 24, cap: true },
      easing: easeInOutQuad,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "wash",
    radiusScale: 1.4,
  },
  soft: {
    id: "soft",
    label: "Soft Airbrush",
    description: "Soft fade. Pressure governs both width and alpha.",
    defaultSize: 24,
    defaultOpacity: 0.35,
    strokeOptions: {
      thinning: 0.85,
      smoothing: 0.6,
      streamline: 0.6,
      simulatePressure: false,
      start: { taper: 16, cap: true },
      end: { taper: 16, cap: true },
      easing: easeInOutQuad,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "soft_airbrush",
    radiusScale: 1.6,
  },
  hard: {
    id: "hard",
    label: "Hard Round",
    description: "Solid round. Constant body, ideal for cel shading and reference lines.",
    defaultSize: 8,
    defaultOpacity: 1,
    strokeOptions: {
      thinning: 0,
      smoothing: 0.6,
      streamline: 0.55,
      simulatePressure: false,
      start: { taper: 0, cap: true },
      end: { taper: 0, cap: true },
      easing: linear,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "hard_round",
    radiusScale: 1.1,
  },
  marker: {
    id: "marker",
    label: "Marker",
    description: "Permanent marker. Subtle bleed, tone builds on overlap.",
    defaultSize: 14,
    defaultOpacity: 0.55,
    strokeOptions: {
      thinning: 0.35,
      smoothing: 0.55,
      streamline: 0.5,
      simulatePressure: false,
      start: { taper: 0, cap: false },
      end: { taper: 0, cap: false },
      easing: linear,
    },
    compositeOperation: "multiply",
    flatFill: true,
    engine: "mypaint",
    brushFile: "marker",
    radiusScale: 1.0,
  },
  smudge: {
    id: "smudge",
    label: "Smudge",
    description:
      "Pulls color from the canvas as you drag. Now actually a smudge — libmypaint reads pixels and re-stamps them.",
    defaultSize: 28,
    defaultOpacity: 1,
    strokeOptions: {
      thinning: 0.6,
      smoothing: 0.8,
      streamline: 0.8,
      simulatePressure: false,
      start: { taper: 12, cap: true },
      end: { taper: 12, cap: true },
      easing: easeInOutQuad,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "smudge",
    radiusScale: 1.2,
  },
  eraser: {
    id: "eraser",
    label: "Eraser",
    description: "Pressure-sensitive eraser. Light touch fades; firm press wipes.",
    defaultSize: 20,
    defaultOpacity: 1,
    strokeOptions: {
      thinning: 0.3,
      smoothing: 0.5,
      streamline: 0.5,
      simulatePressure: false,
      start: { taper: 0, cap: true },
      end: { taper: 0, cap: true },
      easing: linear,
    },
    compositeOperation: "destination-out",
    flatFill: true,
    engine: "mypaint",
    brushFile: "eraser",
    radiusScale: 1.3,
  },
  charcoal: {
    id: "charcoal",
    label: "Charcoal",
    description: "Dustier and darker than the pencil. Heavy buildup, broad strokes.",
    defaultSize: 14,
    defaultOpacity: 0.7,
    strokeOptions: {
      thinning: 0.5,
      smoothing: 0.4,
      streamline: 0.4,
      simulatePressure: false,
      start: { taper: 8, cap: true },
      end: { taper: 12, cap: true },
      easing: easeOutCubic,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "charcoal",
    radiusScale: 1.1,
  },
  pastel: {
    id: "pastel",
    label: "Pastel",
    description: "Broad opaque pastel stick. Painterly buildup, slight tooth.",
    defaultSize: 16,
    defaultOpacity: 0.85,
    strokeOptions: {
      thinning: 0.4,
      smoothing: 0.5,
      streamline: 0.5,
      simulatePressure: false,
      start: { taper: 8, cap: true },
      end: { taper: 8, cap: true },
      easing: easeOutCubic,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "pastel",
    radiusScale: 1.0,
  },
  ballpen: {
    id: "ballpen",
    label: "Ballpoint",
    description: "Thin, consistent ink. Like writing with a Bic.",
    defaultSize: 3,
    defaultOpacity: 0.9,
    strokeOptions: {
      thinning: 0.25,
      smoothing: 0.7,
      streamline: 0.55,
      simulatePressure: false,
      start: { taper: 0, cap: true },
      end: { taper: 4, cap: true },
      easing: linear,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "ballpen",
    radiusScale: 0.7,
  },
  calligraphy: {
    id: "calligraphy",
    label: "Calligraphy",
    description: "Directional thick/thin nib. Vertical strokes thick, horizontals thin.",
    defaultSize: 10,
    defaultOpacity: 1,
    strokeOptions: {
      thinning: 0.6,
      smoothing: 0.6,
      streamline: 0.55,
      simulatePressure: false,
      start: { taper: 6, cap: true },
      end: { taper: 10, cap: true },
      easing: easeOutCubic,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "calligraphy",
    radiusScale: 1.0,
  },
  knife: {
    id: "knife",
    label: "Palette Knife",
    description: "Mixes color from the canvas. No texture — pure color movement.",
    defaultSize: 22,
    defaultOpacity: 1,
    strokeOptions: {
      thinning: 0.4,
      smoothing: 0.7,
      streamline: 0.65,
      simulatePressure: false,
      start: { taper: 4, cap: true },
      end: { taper: 4, cap: true },
      easing: linear,
    },
    compositeOperation: "source-over",
    flatFill: true,
    engine: "mypaint",
    brushFile: "knife",
    radiusScale: 1.2,
  },
};

export const TOOL_ORDER: ToolId[] = [
  "pencil",
  "charcoal",
  "pastel",
  "inking",
  "ballpen",
  "calligraphy",
  "marker",
  "watercolor",
  "soft",
  "hard",
  "knife",
  "smudge",
  "eraser",
];

// Default per-tool starting color. Eraser ignores color but we keep the field
// present so the export schema is uniform.
export const DEFAULT_TOOL_COLORS: Record<ToolId, string> = {
  pencil: "#1c1c1c",
  inking: "#0b0b0b",
  watercolor: "#3a8fd1",
  soft: "#5b3df5",
  hard: "#1c1c1c",
  marker: "#f5a623",
  smudge: "#8b8b8b",
  eraser: "#ffffff",
  charcoal: "#1a1a1a",
  pastel: "#d36e8e",
  ballpen: "#1d2a4f",
  calligraphy: "#101010",
  knife: "#7a4f3c",
};
